var wrapperConfigLoaded = jQuery.Deferred();
var HINTS_KEY;
var MAX_LAYER_FEATURES;
var MAX_QUERY_FEATURES;
var POPUP_TIMEOUT;
var PRINT_TEMPLATE_HTML;
var PRINT_TEMPLATE_PDF;
var PRINT_LEGEND_DEFAULT;
var PRINT_LAYOUT_DEFAULT;
var PRINT_FORMAT_DEFAULT;
var OVERVIEW_MAP_W;
var OVERVIEW_MAP_H;
var DEFAULT_CONTROL;
var SEARCH_WINDOW_H;
var FAST_SEARCH_DEFAULT;
var RESULT_LAYER_STYLE;

configLoaded.then(fillLocalVariables);

function fillLocalVariables() {
  MAX_LAYER_FEATURES = clientConfig.MAX_LAYER_FEATURES;
  MAX_QUERY_FEATURES = clientConfig.MAX_QUERY_FEATURES;
  POPUP_TIMEOUT = clientConfig.POPUP_TIMEOUT;
  PRINT_TEMPLATE_HTML = clientConfig.PRINT_TEMPLATE_HTML;
  PRINT_TEMPLATE_PDF = clientConfig.PRINT_TEMPLATE_PDF;
  PRINT_LEGEND_DEFAULT = clientConfig.PRINT_LEGEND_DEFAULT;
  PRINT_LAYOUT_DEFAULT = clientConfig.PRINT_LAYOUT_DEFAULT;
  PRINT_FORMAT_DEFAULT = clientConfig.PRINT_FORMAT_DEFAULT;
  HINTS_KEY = clientConfig.HINTS_KEY;
  OVERVIEW_MAP_W = clientConfig.OVERVIEW_MAP_W;
  OVERVIEW_MAP_H = clientConfig.OVERVIEW_MAP_H;
  SEARCH_WINDOW_H = clientConfig.SEARCH_WINDOW_H;
  FAST_SEARCH_DEFAULT = clientConfig.FAST_SEARCH_DEFAULT;
  RESULT_LAYER_STYLE = clientConfig.RESULT_LAYER_STYLE;
  wrapperConfigLoaded.resolve();
}
